Develop
valikaev1989/java-explore-with-me pull request #1
Opened 2022-10-30 14:55 UTC by valikaev1989

2022-10-31 13:10 UTC, kukolev requested changes
Общее замечание - в коде совсем нет тестов. Нужно покрыть код тестами.

2022-10-31 13:10 UTC, kukolev commented on server/src/main/java/ru/practicum/server/category/services/CategoryServiceImpl.java
> +        log.info("CategoryService.getAllCategories start");
При логировании лучше добавлять информацию о текущих значениях параметров, чтобы при анализе было понятно о чем идет речь. Иначе в многопользовательских приложениях подобные логи будут просто многократно дублироваться и не будут нести полезной информации. Чтобы это исправить здесь будет полезно добавить значение переменной «pageable».

2022-10-31 13:10 UTC, kukolev commented on server/src/main/java/ru/practicum/server/category/controllers/CategoryControllerAdmin.java
> +        System.out.println("\n");
Логирование нужно делать с помощью логгера, а не просто выводить данные в консоль. Это важно, т.к. тогда можно будет управлять настройками логирования. Нужно поправить.

Аналогично нужно поправить и в остальных подобных местах.

2022-10-31 13:10 UTC, kukolev commented on server/src/main/java/ru/practicum/server/utils/Validation.java
> +public class Validation {
Этот класс нужно переделать. Сейчас в нем слишком много логики:
1. Класс объединяет в себе сразу все репозитории. Получается такой God Object, не отвечающий принципу единственной ответственности.
2. Класс называется Validation, что не отражает его назначение сейчас.
3. Загрузка объектов и их валидация обычно делается в сервисе. Если валидацию хочется вынести в отдельный класс, то выносить нужно именно валидацию, а не загрузку.

2022-10-31 19:03 UTC, valikaev1989 commented on server/src/main/java/ru/practicum/server/category/controllers/CategoryControllerAdmin.java
> +        System.out.println("\n");
сделано

2022-10-31 19:20 UTC, valikaev1989 commented on server/src/main/java/ru/practicum/server/category/services/CategoryServiceImpl.java
> +        log.info("CategoryService.getAllCategories start");
сделано

2022-10-31 20:03 UTC, valikaev1989 commented on server/src/main/java/ru/practicum/server/utils/Validation.java
> +public class Validation {
сделано

2022-11-01 16:09 UTC, kukolev requested changes

2022-11-01 16:09 UTC, kukolev commented on server/src/main/java/ru/practicum/server/compilation/services/CompilationServiceImpl.java
> +        System.out.println(compilation);
Логирование нужно делать с помощью логгера, а не просто выводить данные в консоль. Это важно, т.к. тогда можно будет управлять настройками логирования. Нужно поправить.

2022-11-01 16:09 UTC, kukolev commented on server/src/main/java/ru/practicum/server/compilation/controllers/CompilationControllerAdmin.java
> +        log.info("\nCompilationControllerAdmin.toUnfixCompilation compId:{}", compId);
Судя по всему \n нужен для того, чтобы строки в логе смотрелись разрывно - визуально отстояли одна от другой. Если так, то это нужно исправить, т.к. на практике в реальной разработке это будет только вредить. Лог должен быть компактным, чтобы на экране было как можно больше информации. Это поможет быстрее найти ошибку.

Нужно поправить здесь и в остальных местах.

2022-11-01 16:09 UTC, kukolev commented on server/src/main/java/ru/practicum/server/compilation/controllers/CompilationControllerAdmin.java
> +        log.info("\nCompilationControllerAdmin.deleteEventFromCompilation compId:{}, eventId:{}", compId, eventId);
Прописывать название класса не нужно, т.к. логгер по умолчанию и так выведет название класса в лог. При желании можно настроить и вывод названия метода.

Это нужно поправить здесь и в остальных подобных местах.

2022-11-01 16:09 UTC, kukolev commented on server/src/main/java/ru/practicum/server/clientStatistics/BaseClient.java
> +            return ResponseEntity.status(ex.getStatusCode()).body(ex.getResponseBodyAsByteArray());
Здесь лучше добавить warning, т.к. это явно нестандартная ситуация. Думаю это нужно отразить в логах.

2022-11-01 16:09 UTC, kukolev commented on server/src/main/java/ru/practicum/server/utils/CategoryValidator.java
> +        ids.forEach(id -> log.info("{}", id));
Распечатывать в логе все возможные категории это, возможно, плохая идея, т.к. категорий может быть очень много и лог будет сильно разрастаться.

2022-11-01 18:17 UTC, valikaev1989 commented on server/src/main/java/ru/practicum/server/compilation/controllers/CompilationControllerAdmin.java
> +        log.info("\nCompilationControllerAdmin.toUnfixCompilation compId:{}", compId);
сделано

2022-11-01 18:17 UTC, valikaev1989 commented on server/src/main/java/ru/practicum/server/compilation/services/CompilationServiceImpl.java
> +        System.out.println(compilation);
сделано

2022-11-01 18:50 UTC, valikaev1989 commented on server/src/main/java/ru/practicum/server/clientStatistics/BaseClient.java
> +            return ResponseEntity.status(ex.getStatusCode()).body(ex.getResponseBodyAsByteArray());
сделано

2022-11-01 18:59 UTC, valikaev1989 commented on server/src/main/java/ru/practicum/server/compilation/controllers/CompilationControllerAdmin.java
> +        log.info("\nCompilationControllerAdmin.deleteEventFromCompilation compId:{}, eventId:{}", compId, eventId);
сделано

2022-11-01 18:59 UTC, valikaev1989 commented on server/src/main/java/ru/practicum/server/utils/CategoryValidator.java
> +        ids.forEach(id -> log.info("{}", id));
сделано

2022-11-04 15:57 UTC, merged